[pytest]
testpaths = tests
pythonpath = .
addopts = --cov=. --cov-report=term-missing --cov-report=html:coverage --cov-report=xml:coverage.xml

[coverage:run]
omit =
    tests/*
    venv/*

[coverage:report]
omit =
    tests/*
    venv/*
